export const platformList = [
    {
        "id": 369,
        "siteName": "ООО ТК «Медовые водопады»",
        "coordinates": "[43.884412,42.587132]",
        "address": "369387, Карачаево-черкесская Р",
        "area": 30000.0,
        "description": "",
        "typeOfActivity": "Сельскохозяйственное использов",
        "formOfTransaction": "Продажа",
        "siteType": "sites",
        "siteTypeObj": "sites",
        "supportMeasures": null,
        "gasSupply": "no",
        "electricitySupply": "yes",
        "waterSupply": "yes",
        "responsiblePerson": "+7 (928) 654-44-77",
        "contactsOfPesponsiblePerson": "ООО ТК «Медовые водопады»",
        "photo": null,
        "region": "default_value"
    }
]

export const areasList = [
    {
        "id": 94,
        "siteName": "Земельный участок п. Мара-Аягъы",
        "coordinates": "[43.783612, 41.917213]",
        "typeOfProperty": null,
        "location": "Российская Федерация, Карачаев",
        "area": 17719.0,
        "cadastralNumber": "09:10:0070109:678",
        "cadastralValue": "8382150.14",
        "landCategory": "Земли населенных пунктов",
        "typeOfAuthorizedUseOfLand": "Под строительство цеха по розл",
        "documents": null,
        "photo": null,
        "photo2": null,
        "photo3": null,
        "photo4": null,
        "region": "default_value",
        "siteType": "participants"
    },
    {
        "id": 95,
        "siteName": "Карачаевск земельный участок",
        "coordinates": "[43.761930, 41.914511]",
        "typeOfProperty": null,
        "location": "Карачаевск, ул. Курджиева, 7",
        "area": 17187.0,
        "cadastralNumber": "09:10:0070110:5389",
        "cadastralValue": "17273450.61",
        "landCategory": "Земли населенных пунктов",
        "typeOfAuthorizedUseOfLand": "для обслуживания производствен",
        "documents": null,
        "photo": null,
        "photo2": null,
        "photo3": null,
        "photo4": null,
        "region": "default_value",
        "siteType": "participants"
    },
    {
        "id": 96,
        "siteName": "Карачаевск земельный участок",
        "coordinates": "[43.775521, 41.914178]",
        "typeOfProperty": null,
        "location": "Карачаевск, ул. Эркенова, д. 9",
        "area": 3472.0,
        "cadastralNumber": "09:10:0070110:722",
        "cadastralValue": "1955812.32",
        "landCategory": "Земли населенных пунктов",
        "typeOfAuthorizedUseOfLand": "Под объектами коммунального хо",
        "documents": null,
        "photo": "/media/map/objectImages/hU7w7gKgU8lytqOeHRSrGw.jpeg",
        "photo2": null,
        "photo3": null,
        "photo4": null,
        "region": "default_value",
        "siteType": "participants"
    }
]

export const electricitySupply = [
    {
        "id": 29,
        "siteName": "ПС 110/10 кВ Заречная",
        "coordinates": "[44.214055, 41.99930]",
        "nameOfCP": "ПС 110/10 кВ Заречная",
        "settlement": "п. Заречный",
        "numberAndRatedCapacityOfInstalledTransformers": "1х6,3",
        "capacityDeficitSurplus": "1,2",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 30,
        "siteName": "ПС 110/10 кВ Ильичевская",
        "coordinates": "[44.179277, 42.189916]",
        "nameOfCP": "ПС 110/10 кВ Ильичевская",
        "settlement": "Прикубанский район",
        "numberAndRatedCapacityOfInstalledTransformers": "1х6,3",
        "capacityDeficitSurplus": "4,2",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 31,
        "siteName": "ПС 110/10 кВ ПРП",
        "coordinates": "Добавить маркер: \r\n[44.213541,42.070186]",
        "nameOfCP": "ПС 110/10 кВ ПРП",
        "settlement": "г. Черкесск",
        "numberAndRatedCapacityOfInstalledTransformers": "1х25 и 1х16",
        "capacityDeficitSurplus": "14,2",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 32,
        "siteName": "ПС 110/10/6 кВ Северная",
        "coordinates": "[44.250181,42.04876]",
        "nameOfCP": "ПС 110/10/6 кВ Северная",
        "settlement": "г. Черкесск",
        "numberAndRatedCapacityOfInstalledTransformers": "2х25",
        "capacityDeficitSurplus": "4,2",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 33,
        "siteName": "ПС 110/10 кВ  Южная",
        "coordinates": "[44.198754, 42.046194]",
        "nameOfCP": "ПС 110/10 кВ  Южная",
        "settlement": "г. Черкесск",
        "numberAndRatedCapacityOfInstalledTransformers": "2х40",
        "capacityDeficitSurplus": "12,4",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 34,
        "siteName": "ПС 110/6 кВ Головная",
        "coordinates": "[44.040861, 41.968222]",
        "nameOfCP": "ПС 110/6 кВ Головная",
        "settlement": "г. Усть-Джегута",
        "numberAndRatedCapacityOfInstalledTransformers": "2х6,3",
        "capacityDeficitSurplus": "2,2",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 35,
        "siteName": "ПС 35/10 кВ Николаевская",
        "coordinates": "[44.120968, 42.119407]",
        "nameOfCP": "ПС 35/10 кВ Николаевская",
        "settlement": "с. Николаевское",
        "numberAndRatedCapacityOfInstalledTransformers": "2х2,5",
        "capacityDeficitSurplus": "1,1",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 36,
        "siteName": "ПС 35/10 кВ Новая-Джегута",
        "coordinates": "[44.017435, 42.035313]",
        "nameOfCP": "ПС 35/10 кВ Новая-Джегута",
        "settlement": "а. Новая-Джегута",
        "numberAndRatedCapacityOfInstalledTransformers": "2х2,5",
        "capacityDeficitSurplus": "0,6",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 37,
        "siteName": "ПС 110/10/6 кВ Ток Москвы",
        "coordinates": "[44.019663, 41.943604]",
        "nameOfCP": "ПС 110/10/6 кВ Ток Москвы",
        "settlement": "территория т/к \"Южный\"",
        "numberAndRatedCapacityOfInstalledTransformers": "1х10 и 1х16",
        "capacityDeficitSurplus": "5,1",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 38,
        "siteName": "ПС 110/35/10/6кВ  Усть-Джегута",
        "coordinates": "[44.114194, 41.998138]",
        "nameOfCP": "ПС 110/35/10/6кВ  Усть-Джегута",
        "settlement": "г. Усть-Джегута",
        "numberAndRatedCapacityOfInstalledTransformers": "2х20",
        "capacityDeficitSurplus": "6,4",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 39,
        "siteName": "ПС 110/6 кВ Цементная",
        "coordinates": "[44.1227842, 42.007796]",
        "nameOfCP": "ПС 110/6 кВ Цементная",
        "settlement": "территория Цемзавода",
        "numberAndRatedCapacityOfInstalledTransformers": "2х40",
        "capacityDeficitSurplus": "23,9",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 40,
        "siteName": "ПС 35/10 кВ Эльтаркач",
        "coordinates": "[43.988859, 42.134365]",
        "nameOfCP": "ПС 35/10 кВ Эльтаркач",
        "settlement": "а. Эльтаркач",
        "numberAndRatedCapacityOfInstalledTransformers": "1х2,5",
        "capacityDeficitSurplus": "1,8",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 41,
        "siteName": "ПС 110/10/6 кВ Береговая",
        "coordinates": "[44.262031, 42.253763]",
        "nameOfCP": "ПС 110/10/6 кВ Береговая",
        "settlement": "п. Кавказский",
        "numberAndRatedCapacityOfInstalledTransformers": "2х10",
        "capacityDeficitSurplus": "8,5",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 42,
        "siteName": "ПС 110/10 кВ Кавказская",
        "coordinates": "[44.263484, 42.221177]",
        "nameOfCP": "ПС 110/10 кВ Кавказская",
        "settlement": "п. Кавказский",
        "numberAndRatedCapacityOfInstalledTransformers": "2х6,3",
        "capacityDeficitSurplus": "4,4",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 43,
        "siteName": "ПС 110/10 кВ Майская",
        "coordinates": "[44.299759, 42.42299]",
        "nameOfCP": "ПС 110/10 кВ Майская",
        "settlement": "п. Майский",
        "numberAndRatedCapacityOfInstalledTransformers": "2х6,3",
        "capacityDeficitSurplus": "5,0",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 44,
        "siteName": "ПС 110/10/6 кВ Октябрьская",
        "coordinates": "[44.24729, 42.485443]",
        "nameOfCP": "ПС 110/10/6 кВ Октябрьская",
        "settlement": "п.Октябрьский",
        "numberAndRatedCapacityOfInstalledTransformers": "2х10",
        "capacityDeficitSurplus": "7,5",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 45,
        "siteName": "ПС 110/10/6 кВ Октябрьская",
        "coordinates": "[44.24729, 42.485443]",
        "nameOfCP": "ПС 110/10/6 кВ Октябрьская",
        "settlement": "п.Октябрьский",
        "numberAndRatedCapacityOfInstalledTransformers": "2х10",
        "capacityDeficitSurplus": "7,5",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 46,
        "siteName": "ПС 35/10 кВ Бесленей",
        "coordinates": "[44.243992, 41.747195]",
        "nameOfCP": "ПС 35/10 кВ Бесленей",
        "settlement": "а. Бесленей",
        "numberAndRatedCapacityOfInstalledTransformers": "2х2,5",
        "capacityDeficitSurplus": "1,6",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 47,
        "siteName": "ПС 35/10кВ Икон-Халк",
        "coordinates": "[44.289537, 41.909628]",
        "nameOfCP": "ПС 35/10кВ Икон-Халк",
        "settlement": "а. Икон-Халк",
        "numberAndRatedCapacityOfInstalledTransformers": "1х2,5",
        "capacityDeficitSurplus": "1,4",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 48,
        "siteName": "ПС 35/10кВ Кубан-Халк",
        "coordinates": "[44.386749, 41.938802]",
        "nameOfCP": "ПС 35/10кВ Кубан-Халк",
        "settlement": "а. Эркин-Шахар",
        "numberAndRatedCapacityOfInstalledTransformers": "2х4",
        "capacityDeficitSurplus": "2,1",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 49,
        "siteName": "ПС 35/10/35 кВ Полевая",
        "coordinates": "[44.391737, 41.893345]",
        "nameOfCP": "ПС 35/10/35 кВ Полевая",
        "settlement": "Смертельная балка",
        "numberAndRatedCapacityOfInstalledTransformers": "1х2,5",
        "capacityDeficitSurplus": "2,1",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 50,
        "siteName": "ПС 35/10 кВ Псаучье-Дахе",
        "coordinates": "[44.219519, 41.882138]",
        "nameOfCP": "ПС 35/10 кВ Псаучье-Дахе",
        "settlement": "п. Псауче-Дахе",
        "numberAndRatedCapacityOfInstalledTransformers": "2х4",
        "capacityDeficitSurplus": "2,7",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 51,
        "siteName": "ПС 110/10 кВ Садовая",
        "coordinates": "[44.312083, 42.0508333]",
        "nameOfCP": "ПС 110/10 кВ Садовая",
        "settlement": "с. Садовое",
        "numberAndRatedCapacityOfInstalledTransformers": "1х10 и.1х6,3",
        "capacityDeficitSurplus": "3,5",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 52,
        "siteName": "ПС 110/35/10 кВ Старокувинская",
        "coordinates": "[44.328888, 41.76978]",
        "nameOfCP": "ПС 110/35/10 кВ Старокувинская",
        "settlement": "а. Старокувинск",
        "numberAndRatedCapacityOfInstalledTransformers": "1х6,3",
        "capacityDeficitSurplus": "5,0",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 53,
        "siteName": "ПС 110/35/10/6 кВ Эркин-Шахар",
        "coordinates": "[44.378111, 41.966277]",
        "nameOfCP": "ПС 110/35/10/6 кВ Эркин-Шахар",
        "settlement": "п. Эркин-Шахар",
        "numberAndRatedCapacityOfInstalledTransformers": "1х10 и 1х16",
        "capacityDeficitSurplus": "1,4",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 54,
        "siteName": "ПС 35/10 кВ Эрсакон",
        "coordinates": "[44.416872, 41.779176]",
        "nameOfCP": "ПС 35/10 кВ Эрсакон",
        "settlement": "а. Эрсакон",
        "numberAndRatedCapacityOfInstalledTransformers": "1х4 и 1х6,3",
        "capacityDeficitSurplus": "2,6",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 55,
        "siteName": "ПС 110/10/6 кВ Академическая",
        "coordinates": "[43.816444, 41.359944]",
        "nameOfCP": "ПС 110/10/6 кВ Академическая",
        "settlement": "ст. Сторожевая",
        "numberAndRatedCapacityOfInstalledTransformers": "2х25",
        "capacityDeficitSurplus": "18,7",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 56,
        "siteName": "ПС 35/10кВ Архыз",
        "coordinates": "[43.567022, 41.297872]",
        "nameOfCP": "ПС 35/10кВ Архыз",
        "settlement": "п. Архыз",
        "numberAndRatedCapacityOfInstalledTransformers": "2х4",
        "capacityDeficitSurplus": "-1,5",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 57,
        "siteName": "ПС 35/10кВ Буково",
        "coordinates": "[43.681316, 41.463709]",
        "nameOfCP": "ПС 35/10кВ Буково",
        "settlement": "Нижний Архыз",
        "numberAndRatedCapacityOfInstalledTransformers": "1х2,5",
        "capacityDeficitSurplus": "1,5",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 58,
        "siteName": "ПС 110/35/10 кВ Зеленчук",
        "coordinates": "[43.857472, 41.616861]",
        "nameOfCP": "ПС 110/35/10 кВ Зеленчук",
        "settlement": "ст. Зеленчукская",
        "numberAndRatedCapacityOfInstalledTransformers": "1х16 и 1х20",
        "capacityDeficitSurplus": "-1,3",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 59,
        "siteName": "ПС 35/10 кВ Исправная",
        "coordinates": "[44.055179, 41.611409]",
        "nameOfCP": "ПС 35/10 кВ Исправная",
        "settlement": "ст. Исправная",
        "numberAndRatedCapacityOfInstalledTransformers": "1х4",
        "capacityDeficitSurplus": "2,7",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 60,
        "siteName": "ПС 35/10кВ Кардоникская",
        "coordinates": "[43.862777, 41.706426]",
        "nameOfCP": "ПС 35/10кВ Кардоникская",
        "settlement": "ст. Кардоникская",
        "numberAndRatedCapacityOfInstalledTransformers": "1х6,3",
        "capacityDeficitSurplus": "3,5",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 61,
        "siteName": "ПС 110/10кВ Кош-Хабль",
        "coordinates": "[44.129407, 41.840083]",
        "nameOfCP": "ПС 110/10кВ Кош-Хабль",
        "settlement": "а. Кош-Хабль",
        "numberAndRatedCapacityOfInstalledTransformers": "2х6,3",
        "capacityDeficitSurplus": "4,4",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 62,
        "siteName": "ПС 110/10кВ Курджиново",
        "coordinates": "[43.988042, 40.970888]",
        "nameOfCP": "ПС 110/10кВ Курджиново",
        "settlement": "с. Псемен",
        "numberAndRatedCapacityOfInstalledTransformers": "1х6,3",
        "capacityDeficitSurplus": "3,5",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 63,
        "siteName": "ПС 110/10кВ Маруха",
        "coordinates": "[43.79503, 41.656847]",
        "nameOfCP": "ПС 110/10кВ Маруха",
        "settlement": "с. Маруха",
        "numberAndRatedCapacityOfInstalledTransformers": "1х2,5",
        "capacityDeficitSurplus": "1,2",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 64,
        "siteName": "ПС 110/35/6кВ Преградная",
        "coordinates": "[43.821513, 41.586647]",
        "nameOfCP": "ПС 110/35/6кВ Преградная",
        "settlement": "п. Медногорский",
        "numberAndRatedCapacityOfInstalledTransformers": "2х25",
        "capacityDeficitSurplus": "10,9",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 65,
        "siteName": "ПС 35/10 кВ Ратан",
        "coordinates": "[43.821513, 41.586647]",
        "nameOfCP": "ПС 35/10 кВ Ратан",
        "settlement": "ст. Зеленчукская",
        "numberAndRatedCapacityOfInstalledTransformers": "1х4",
        "capacityDeficitSurplus": "2,4",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 66,
        "siteName": "ПС 110/10 кВ Салихо",
        "coordinates": "[43.974052, 41.184249]",
        "nameOfCP": "ПС 110/10 кВ Салихо",
        "settlement": "ст. Преградная",
        "numberAndRatedCapacityOfInstalledTransformers": "1х2,5",
        "capacityDeficitSurplus": "2,1",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 67,
        "siteName": "ПС 110/10 кВ Сторожевая",
        "coordinates": "[43.886859, 41.469183]",
        "nameOfCP": "ПС 110/10 кВ Сторожевая",
        "settlement": "ст.Сторожевая",
        "numberAndRatedCapacityOfInstalledTransformers": "2х6,3",
        "capacityDeficitSurplus": "3,6",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 68,
        "siteName": "ПС 110/10 кВ Хабез",
        "coordinates": "[44.025886, 41.761693]",
        "nameOfCP": "ПС 110/10 кВ Хабез",
        "settlement": "а. Хабез",
        "numberAndRatedCapacityOfInstalledTransformers": "2х6,3",
        "capacityDeficitSurplus": "1,2",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 69,
        "siteName": "ПС 110/10 кВ Чапалы",
        "coordinates": "[43.713339, 41.241186]",
        "nameOfCP": "ПС 110/10 кВ Чапалы",
        "settlement": "ст. Сторожевая",
        "numberAndRatedCapacityOfInstalledTransformers": "2х16",
        "capacityDeficitSurplus": "13,3",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 70,
        "siteName": "ПС 35/10 кВ Электроизолит",
        "coordinates": "[43.874639, 41.694079]",
        "nameOfCP": "ПС 35/10 кВ Электроизолит",
        "settlement": "ст. Кардоникская",
        "numberAndRatedCapacityOfInstalledTransformers": "1х4",
        "capacityDeficitSurplus": "3,3",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 71,
        "siteName": "ПС 110/10 кВ БСР",
        "coordinates": "[43.863240, 41.852082]",
        "nameOfCP": "ПС 110/10 кВ БСР",
        "settlement": "а. Кумыш",
        "numberAndRatedCapacityOfInstalledTransformers": "1х2,5",
        "capacityDeficitSurplus": "2,2",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 72,
        "siteName": "ПС 110/10 кВ Гоначхир",
        "coordinates": "[43.33275, 41.6674]",
        "nameOfCP": "ПС 110/10 кВ Гоначхир",
        "settlement": "179км. ФАД Невинномыск - Домба",
        "numberAndRatedCapacityOfInstalledTransformers": "2х10",
        "capacityDeficitSurplus": "6,2",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 73,
        "siteName": "ПС 110/10 кВ Горная",
        "coordinates": "[43.41637, 41.735123]",
        "nameOfCP": "ПС 110/10 кВ Горная",
        "settlement": "г. Теберда,",
        "numberAndRatedCapacityOfInstalledTransformers": "2х6,3",
        "capacityDeficitSurplus": "4,1",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 74,
        "siteName": "ПС 110/10 кВ Горная",
        "coordinates": "[43.41637, 41.735123]",
        "nameOfCP": "ПС 110/10 кВ Горная",
        "settlement": "г. Теберда,",
        "numberAndRatedCapacityOfInstalledTransformers": "2х6,3",
        "capacityDeficitSurplus": "4,1",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 75,
        "siteName": "ПС 110/10 кВ \"Касаева\"",
        "coordinates": "[43.761794, 41.895645]",
        "nameOfCP": "ПС 110/10 кВ \"Касаева\"",
        "settlement": "г. Карачаевск",
        "numberAndRatedCapacityOfInstalledTransformers": "1х16 и 1х63",
        "capacityDeficitSurplus": "7,6",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 76,
        "siteName": "ПС 110/10 кВ Кубанская",
        "coordinates": "[43.818076, 41.899399]",
        "nameOfCP": "ПС 110/10 кВ Кубанская",
        "settlement": "Н. Карачай,",
        "numberAndRatedCapacityOfInstalledTransformers": "1х10 и 1х16",
        "capacityDeficitSurplus": "2,6",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 77,
        "siteName": "ПС 110/35/10 кВ Поляна",
        "coordinates": "[43.551670, 42.132131]",
        "nameOfCP": "ПС 110/35/10 кВ Поляна",
        "settlement": "п. Эльбрусский,",
        "numberAndRatedCapacityOfInstalledTransformers": "1х2,5 и.1х6,3",
        "capacityDeficitSurplus": "0,8",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 78,
        "siteName": "ПС 110/10 кВ Сары-Тюз",
        "coordinates": "[43.908961, 41.879662]",
        "nameOfCP": "ПС 110/10 кВ Сары-Тюз",
        "settlement": "п. Правокубанский",
        "numberAndRatedCapacityOfInstalledTransformers": "1х10",
        "capacityDeficitSurplus": "6,1",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 79,
        "siteName": "ПС 110/10 кВ Теберда",
        "coordinates": "[43.45865, 41.744672]",
        "nameOfCP": "ПС 110/10 кВ Теберда",
        "settlement": "г. Теберда",
        "numberAndRatedCapacityOfInstalledTransformers": "1х10",
        "capacityDeficitSurplus": "4,9",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 80,
        "siteName": "ПС 35/6 кВ Учкулан",
        "coordinates": "[43.46306, 42.098342]",
        "nameOfCP": "ПС 35/6 кВ Учкулан",
        "settlement": "а. Учкулан",
        "numberAndRatedCapacityOfInstalledTransformers": "1х2,5",
        "capacityDeficitSurplus": "0,9",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 81,
        "siteName": "ПС 35/10 кВ Худес",
        "coordinates": "[43.583972, 42.299238]",
        "nameOfCP": "ПС 35/10 кВ Худес",
        "settlement": "урочище Худес",
        "numberAndRatedCapacityOfInstalledTransformers": "1х2,5",
        "capacityDeficitSurplus": "2,2",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 82,
        "siteName": "ПС 35/10 кВ Биче-Сын",
        "coordinates": "[43.635568, 42.424683]",
        "nameOfCP": "ПС 35/10 кВ Биче-Сын",
        "settlement": "урочище Биче-Сын",
        "numberAndRatedCapacityOfInstalledTransformers": "1х1,6",
        "capacityDeficitSurplus": "1,4",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 83,
        "siteName": "ПС 35/10 кВ Конзаводская",
        "coordinates": "[43.939098, 42.617395]",
        "nameOfCP": "ПС 35/10 кВ Конзаводская",
        "settlement": "с. Красный Курган",
        "numberAndRatedCapacityOfInstalledTransformers": "1х4",
        "capacityDeficitSurplus": "2,4",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 84,
        "siteName": "ПС 35/10 кВ Красный Восток",
        "coordinates": "[43.953648, 42.276031]",
        "nameOfCP": "ПС 35/10 кВ Красный Восток",
        "settlement": "с. Красный Восток",
        "numberAndRatedCapacityOfInstalledTransformers": "2х4",
        "capacityDeficitSurplus": "2,8",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 85,
        "siteName": "ПС 35/10 кВ Кичи-Балык",
        "coordinates": "[43.790092, 42.655314]",
        "nameOfCP": "ПС 35/10 кВ Кичи-Балык",
        "settlement": "а. Кичи-Балык",
        "numberAndRatedCapacityOfInstalledTransformers": "2х2,5",
        "capacityDeficitSurplus": "2,1",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 86,
        "siteName": "ПС 35/10 кВ Кичи-Балык",
        "coordinates": "[43.790092, 42.655314]",
        "nameOfCP": "ПС 35/10 кВ Кичи-Балык",
        "settlement": "а. Кичи-Балык",
        "numberAndRatedCapacityOfInstalledTransformers": "2х2,5",
        "capacityDeficitSurplus": "2,1",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 87,
        "siteName": "ПС 35/10 кВ Первомайская",
        "coordinates": "[43.944147,42.527793]",
        "nameOfCP": "ПС 35/10 кВ Первомайская",
        "settlement": "с. Учкекен",
        "numberAndRatedCapacityOfInstalledTransformers": "2х4",
        "capacityDeficitSurplus": "1,8",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 88,
        "siteName": "ПС 35/10 кВ Терезе",
        "coordinates": "[43.926633, 42.418217]",
        "nameOfCP": "ПС 35/10 кВ Терезе",
        "settlement": "с.Терезе",
        "numberAndRatedCapacityOfInstalledTransformers": "2х2,5",
        "capacityDeficitSurplus": "0,2",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 89,
        "siteName": "ПС 110/35/10 кВ Учкекен",
        "coordinates": "[43.940385, 42.533502]",
        "nameOfCP": "ПС 110/35/10 кВ Учкекен",
        "settlement": "с. Учкекен",
        "numberAndRatedCapacityOfInstalledTransformers": "1х16",
        "capacityDeficitSurplus": "0,5",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 90,
        "siteName": "ПС 35/6 кВ Эшкакон",
        "coordinates": "[43.877752, 42.462723]",
        "nameOfCP": "ПС 35/6 кВ Эшкакон",
        "settlement": "п. Эшкакон",
        "numberAndRatedCapacityOfInstalledTransformers": "2х1,6",
        "capacityDeficitSurplus": "1,3",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 91,
        "siteName": "ПС 110/10 кВ Горный Воздух",
        "coordinates": "[43.703444, 41.924236]",
        "nameOfCP": "ПС 110/10 кВ Горный Воздух",
        "settlement": "а. Каменномост",
        "numberAndRatedCapacityOfInstalledTransformers": "1х2,5",
        "capacityDeficitSurplus": "1,6",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 92,
        "siteName": "ПС 110/10 кВ Лунная Поляна",
        "coordinates": "[43.554416, 41.265831]",
        "nameOfCP": "ПС 110/10 кВ Лунная Поляна",
        "settlement": "с. Архыз",
        "numberAndRatedCapacityOfInstalledTransformers": "2х40",
        "capacityDeficitSurplus": "26,6",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    },
    {
        "id": 93,
        "siteName": "ПС 110/10 кВ Романтик",
        "coordinates": "[43.538622, 41.195867]",
        "nameOfCP": "ПС 110/10 кВ Романтик",
        "settlement": "с. Архыз",
        "numberAndRatedCapacityOfInstalledTransformers": "2х16",
        "capacityDeficitSurplus": "11,1",
        "siteType": "electricitySupply",
        "photo": null,
        "region": "default_value"
    }
]